//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace searchIEEE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/oui/oui.csv")]
        public string IEEE_MAL {
            get {
                return ((string)(this["IEEE_MAL"]));
            }
            set {
                this["IEEE_MAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/oui28/mam.csv")]
        public string IEEE_MAM {
            get {
                return ((string)(this["IEEE_MAM"]));
            }
            set {
                this["IEEE_MAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/oui36/oui36.csv")]
        public string IEEE_MAS {
            get {
                return ((string)(this["IEEE_MAS"]));
            }
            set {
                this["IEEE_MAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/iab/iab.csv")]
        public string IEEE_IAB {
            get {
                return ((string)(this["IEEE_IAB"]));
            }
            set {
                this["IEEE_IAB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/cid/cid.csv")]
        public string IEEE_CID {
            get {
                return ((string)(this["IEEE_CID"]));
            }
            set {
                this["IEEE_CID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/ethertype/eth.csv")]
        public string IEEE_Ethertype {
            get {
                return ((string)(this["IEEE_Ethertype"]));
            }
            set {
                this["IEEE_Ethertype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/manid/manid.csv")]
        public string IEEE_Manufacturer {
            get {
                return ((string)(this["IEEE_Manufacturer"]));
            }
            set {
                this["IEEE_Manufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://standards.ieee.org/develop/regauth/bopid/opid.csv")]
        public string IEEE_Operator {
            get {
                return ((string)(this["IEEE_Operator"]));
            }
            set {
                this["IEEE_Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEEE_LocalDB {
            get {
                return ((string)(this["IEEE_LocalDB"]));
            }
            set {
                this["IEEE_LocalDB"] = value;
            }
        }
    }
}
